# ---------------- dataset ----------------
dataset:
  family: atari                   # one of: atari | procgen | mujoco | dm_control
  id: atari/krull/expert-v0       # full Minari ID
  n_ctx: 4                        # frames in the temporal window

# ---------------- model ------------------
model:
  img_res: 64                     # output size of decoder
  enc_out: 512                    # dim of CLIP CLS token
  dec_hlat: 256                   # hidden channels inside decoder
  proj_dim: 128                   # projector dim for InfoNCE

# ---------------- training ---------------
training:
  epochs: 12
  batch: 256
  lr: 1.0e-4
  unfreeze: 2                     # last ViT blocks to fine-tune
  temperature: 0.07

# ---------------- output -----------------
output:
  base_dir: checkpoints           # root folder for all runs

# python enc_dec_clip.py --cfg pretrain_cfg.yaml