# ---------- global ----------
model:
  img_res: 64        # Decoder output size H=W=64
  enc_out: 1024      # Latent size expected by Drama
  dec_hlat: 256      # Hidden channels inside decoder
  proj_dim: 128      # Projector dim for InfoNCE

dataset:
  n_ctx: 4           # number of successive frames (anchor/pos/neg)

training:
  epochs: 12
  batch: 256
  lr: 1.0e-4
  unfreeze: 2        # last ViT block fine-tuned
  temperature: 0.07

output:
  base_dir: checkpoints